# Ermand's Brew Arsenal — mirrors brew-packages.html
# Install: brew bundle install --file=Brewfile
# Some formulae/casks may need extra taps; if `brew bundle` errors, run the suggested `brew tap ...` and retry.

# --- Formulae ---
brew "acli"
brew "act"
brew "bash"
brew "bat"
brew "btop"
brew "direnv"
brew "dotnet"
brew "dust"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "glab"
brew "glib"
brew "go"
brew "htop"
brew "hurl"
brew "hyperfine"
brew "imagemagick"
brew "jq"
brew "just"
brew "k6"
brew "lazydocker"
brew "lazygit"
brew "mole"
brew "neovim"
brew "opencode"
brew "pnpm"
brew "pyenv"
brew "python@3.14"
brew "redis"
brew "ripgrep"
brew "ruby"
brew "sqlite"
brew "starship"
brew "taproom"
brew "telnet"
brew "tmux"
brew "tokei"
brew "tree-sitter"
brew "wget"
brew "worktrunk"
brew "yarn"
brew "yazi"
brew "yt-dlp"
brew "zoxide"
brew "zsh-completions"

# --- Casks ---
cask "aerospace"
cask "android-platform-tools"
cask "bruno"
cask "claude-code"
cask "electrum"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "karabiner-elements"
cask "numi"
cask "t3-code"
